### ISSUE TITLE
forEach metod for Result

### ISSUE THREAD

**Issue by NEWESTERS** [true-myth/true-myth#101]
I've tried [monet.js](https://monet.github.io/monet.js/), which has [forEach method](https://github.com/monet/monet.js/blob/master/docs/EITHER.md#foreach) for applying side-effects to wrapped value, but it breaks chaining.

With `true-myth` i am only able to do this only in imperative way:
```typescript
const a = Result.ok("FOO");

if(a.isOk()) {
  console.log(a.value);
}

a.map((value) => value.toLowerCase()) // Result.ok("foo");
```
Or by returning same value in `map`:
```typescript
Result.ok("FOO")
  .map((value) => {
    console.log(value);
    return value;
  })
  .map((value) => value.toLowerCase()) // Result.ok("foo")
```
I'd like to perform side-effects like this:
```typescript
Result.ok("FOO")
  .forEach(console.log)
  .map((value) => value.toLowerCase()) // Result.ok("foo")
```
And the same thing for `err`:
```typescript
Result.err("Error")
  .forEachErr(console.log)
```

**Comment by chriskrycho** [comment]
Hi @NEWESTERS, that’s an interesting suggestion. At first blush I dislike it because it *does* break the functional purity that the types otherwise operate with, but I will give it some time and think on it. I definitely get the appeal from a pragmatic point of view!

As an alternative, you can write a standalone function which does this for you in a composable way; I’ll see if I can write up a simple example here later this evening.

**Comment by NEWESTERS** [comment]
@chriskrycho, i've tried to simplify my real project task and realized that maybe i don't really need this feature.

Although i made [demo](https://codesandbox.io/s/result-example-fkvyi?file=/src/index.ts) to illustrate some synthetic use case.

Also i found `tap` method in [rxjs](https://rxjs.dev/api/operators/tap) very similar to something that i want to get.

**Comment by chriskrycho** [comment]
A stand-alone `tap` is exactly what I had in mind! The nice thing about it is that it doesn’t need to know anything about the context it’s operating in, either! It’ll work just as well with `_.map` as `Result.map`!

You can implement it like this:

```ts
function tap<T>(cb: (value: T) => unknown): (t: T) => T {
  return (t) => {
    cb(t);
    return t;
  };
}
```

Then you can use that like this:

```ts
let log = (val: unknown) => console.log(val);

Maybe.of(42)
  .map(tap(log))
  .map(n => n * 2)
  .map(tap(log));
```

That will print 42 and then 84.

Closing this, but feel free to discuss further or ask further questions!
