### ISSUE TITLE
Importing true-myth/result not possible

### ISSUE THREAD

**Issue by lo1tuma** [true-myth/true-myth#102]
I’ve followed the `README.md` and tried the following import statement `import Result, { err, map, ok, toString } from 'true-myth/result';` which fails with a runtime exception: `Error: Cannot find module 'true-myth/result'`.

The TypeScript compiler doesn’t complain because the respective `.d.ts` file exists, but there is no `result.js` in `node_modules/true-myth` nor any kind of `lib` mapping in the `package.json`.

**Comment by chriskrycho** [comment]
The README also notes that you can’t currently do this in Node, I believe? In any case, you’ll be able to do it 🔜 , once I have some time to finish releasing the next major version. As discussed in #87, we’re planning to update this to target Node 14 LTS and later once Node 12 LTS drops out of support, and at that point we’ll switch to publishing ES Modules only, with `type: "modules"` in `package.json`, and at that point this *will* work correctly!
