### ISSUE TITLE
Broken source maps

### ISSUE THREAD

**Issue by benmccann** [true-myth/true-myth#130]
A user was trying to use `true-myth` with SvelteKit. SvelteKit is powered by Vite. If there's an error in the user's application, Vite will crash upon encountering a broken source map and it appears that `true-myth` may be triggering this behavior.

E.g. I see this in the `index.d.ts` file:
```
{"version":3,"file":"index.d.ts","sourceRoot":"./","sources":["index.ts"],"names":[],"mappings":"AAAA;;;GAGG;AAEH,OAAO,KAAK,cAAc,MAAM,SAAS,CAAC;AAC1C,oBAAY,KAAK,CAAC,CAAC,IAAI,OAAO,SAAS,EAAE,KAAK,CAAC,CAAC,CAAC,CAAC;AAClD,eAAO,MAAM,KAAK,uBAAiB,CAAC;AAEpC,OAAO,KAAK,eAAe,MAAM,UAAU,CAAC;AAC5C,oBAAY,MAAM,CAAC,CAAC,EAAE,CAAC,IAAI,OAAO,UAAU,EAAE,MAAM,CAAC,CAAC,EAAE,CAAC,CAAC,CAAC;AAC3D,eAAO,MAAM,MAAM,wBAAkB,CAAC;AAEtC,OAAO,KAAK,aAAa,MAAM,QAAQ,CAAC;AACxC,oBAAY,IAAI,GAAG,OAAO,QAAQ,EAAE,IAAI,CAAC;AACzC,eAAO,MAAM,IAAI,sBAAgB,CAAC"}
```

I think that's an invalid path in for `sources`. There's no `index.ts` in the package root. I see one in `src/index.ts` though

**Comment by chriskrycho** [comment]
Thank you for the report! I believe this is *probably* the result of the patched `package.json`, from @MarcusCemes's writeup on the report on SvelteKit, as the approach taken there isn't something we support *yet*—but if so this is another entry in the "we really need to push all the way into our just-ship-ESM train" bucket (#67 and others). It's also possible this has just been broken for a long time, but no one has caught it. The state of source maps being what they are, that honestly wouldn't surprise me. Either way, I'll try to dig into this later this week.

**Comment by chriskrycho** [comment]
Follow-up: the patched package *shouldn't* be the issue, and I think this must indeed have been broken for a long time.

**Comment by chriskrycho** [comment]
Sorry for the long delay here, folks. I’m working on doing some cleanup over the long weekend here and will hopefully have a v4.1.2 out with various bug fixes today or tomorrow!
