### ISSUE TITLE
Feature request: `Maybe.filter`

### ISSUE THREAD

**Issue by atrick-speedline** [true-myth/true-myth#155]
Would you be interested in adding a filter method to Maybe? I could probably make a PR for it if you want.

For reference, here's the docs for [Option.filter in Rust](https://doc.rust-lang.org/std/option/enum.Option.html#method.filter).

**Comment by chriskrycho** [comment]
Hi @atrick-speedline – probably not, just because I think at this point we're aiming more toward *shrinking* the payload size of the library, and because it's trivial to write it in terms of `andThen` instead:

```ts
import Maybe, { just, nothing } from 'true-myth/maybe';

let isEven = (n: number) => n % 2 === 0;

let m = Maybe.of(123);
let n = m.andThen((num) => isEven(num) ? just(num) : nothing());
```

You can also implement the standalone version trivally yourself:

```ts
import Maybe, { just, nothing } from 'true-myth/maybe';

let filter = <T>(m: Maybe<T>) => (pred: (t: T) => boolean) =>
  m.andThen((t) => pred(t) ? just(t) : nothing());
```
