### ISSUE TITLE
[5.0.0] No unsafelyUnwrap anymore?

### ISSUE THREAD

**Issue by screendriver** [true-myth/true-myth#238]
I can't find it anywhere in the [docs](https://true-myth.js.org/modules/maybe.html) anymore (except in one sentence in [match](https://true-myth.js.org/modules/maybe.html#match)) and it is also not available on `Just` instances and I can't import it anymore with `import { unsafelyUnwrap } from 'true-myth/maybe';`. It is also not mentioned in the [release notes](https://github.com/true-myth/true-myth/releases/tag/v5.0.0).

Was it removed or is it accidentally not exported anymore?

**Comment by chriskrycho** [comment]
Ah, my apologies! I had this in a draft of the release notes and somehow missed it; I will update them with it.

We removed those and all the aliases for them because the way the types work (for quite a while now!) you can always just check `.isJust` and then access `.value` directly the check was `true`. If you need them in a functional chain, and you really want a point free invocation you can replace it with:

- lodash/fp's `_.get(['value'])`

- Ramda's `R.prop('value')`

- this one-liner:

    ```ts
    const value = <T>(just: Just<T>): T => just.value;
    ```

For most purposes, though, just accessing it directly in an `if` body or similar works better *and is faster* than the function call version!

**Comment by chriskrycho** [comment]
Updated the release notes to include this alongside the other aliases (which *were* in the release notes). Thank you!

**Comment by screendriver** [comment]
The main purpose for `unsafelyUnwrap()` are my unit tests. For example:

```ts
test('foo', (t) => {
  const result = nothing<number>(); // my function to test that returns a Maybe
  t.is(42, result.unsafelyUnwrap()); // would fail with "Tried to `unsafelyUnwrap(Nothing)`"
});
```

versus the more verbose version (which has do be done in every single test then)

```ts
test('foo', (t) => {
  const result = nothing<number>(); // my function to test that returns a Maybe
  if (result.isNothing()) {
    t.fail('Result is not a Just');
  }
  t.is(42, result.value);
});
```

Not a big deal but more convenient.

**Comment by chriskrycho** [comment]
Interesting use case! One easier workaround is to explicitly cast it to `Just` or `Nothing` there but I can see the annoyance. Would appreciate your thoughts here as well, @bmakuh!

**Comment by bmakuh** [comment]
I'm assuming the test given is just an "example" test? I definitely see why that removal would be frustrating though

**Comment by screendriver** [comment]
> I'm assuming the test given is just an "example" test?

Yes 🙂 In one of my repositories we have over 5700 unit tests where `Maybe` is often involved. This example here should just showcase a use case where `unsafelyUnwrap()` would make sense.

**Comment by chriskrycho** [comment]
After thinking on and talking about this a bit, @bmakuh and I both concluded that (a) we don't think it's worth shipping this as part of the library (especially on the class, where it can't be tree-shaken!). Instead, if you find this valuable, you can just write this function as a test-only helper:

```ts
import { type Maybe, type Just } from 'true-myth/maybe';

export function unsafelyUnwrap<T>(maybe: Maybe<T>): T {
  return (maybe as Just<T>).value;
}
```

Then you can import that from your test utility package, and do a simple find-and-replace of every `<name>.unsafelyUnwrap()` with `unsafelyUnwrap(<name>);` in your tests.
