### ISSUE TITLE
Idea: Result.try

### ISSUE THREAD

**Issue by bmakuh** [true-myth/true-myth#26]
Right now, to construct a Maybe you can use `Maybe.of` or `Maybe.fromNullable` which are convenience methods that allow you to either construct a `Nothing` if the value is `null` or `undefined`, or a `Just` if it's something else.

For `Result`s, you must manually construct the `Ok` or the `Err` "manually." There is no convenience constructor akin to `of`. I propose a `Result.try` constructor that, as the name suggests, takes in a callback function to execute and if it executes successfully then you would construct an `Ok` or else if an exception is raised then an `Err` is constructed. Think of it as an expression-oriented version of try/catch.

Example:
```ts
import { Result } from 'true-myth'

const willItThrow = Result.try('Oh noes!!1', async () => {
  await fetchMeASammich()
})
```

What happens? If `fetchMeASammich()` fails (Maybe a network error? Maybe the server throws said sandwich across the room instead of hand-delivering it?), `try` will wrap that callback in a `try/catch`, catching the failure and constructing `Result.Err('Oh noes!!1')`. If `fetchMeASammich()` succeeds, `try` will return the return value of the callback wrapped in `Result.Ok`.

### Motivation

Beyond the simple motivation of a single convenience constructor, the True Myth docs use a try/catch block as an example of tedious error handling code. Some codebases use try/catch blocks extensively, and so a streamlined, expression-oriented constructor like this would actually prove quite handy to simplify existing code and smooth the adoption curve for this lib.

Thoughts? Feedback welcome!

**Comment by chriskrycho** [comment]
Resolved via [v2.2.0](https://github.com/true-myth/true-myth/releases/tag/v2.2.0)! I just realized I forgot to close this!
