### ISSUE TITLE
important function `isOk` appears to be missing from the online API docs

### ISSUE THREAD

**Issue by mbylstra** [true-myth/true-myth#305]
![image](https://user-images.githubusercontent.com/702885/154019794-a13b0771-8f44-4564-9799-b16ece35a25f.png)

I had no idea there was an `isOk` function - I discovered the function because I was running into trouble with async/await and found this issue https://github.com/true-myth/true-myth/issues/18, which suggests using `isOk` as a solution. This seems like an important function that should be listed in the docs (in the right column). Actually it seems _essential_ if you want to use async/await or promises.

**Comment by screendriver** [comment]
The same for `Maybe.isJust` and `Maybe.isNothing`.

**Comment by chriskrycho** [comment]
@screendriver thanks! I will poke at this sometime soon and see if I can figure out why. (If you figure out why and open a PR to fix it, that'd also be awesome!)
