### ISSUE TITLE
errors in doc rendering

### ISSUE THREAD

**Issue by psyrendust** [true-myth/true-myth#31]
I was looking at your source code and the jsdoc comments and noticed that there were quite a few issues in the html output.

For instance: https://true-myth.js.org/modules/_maybe_.html#andthen
> ![image](https://user-images.githubusercontent.com/928502/48434229-07ca2400-e72e-11e8-99fa-4ab853e8497d.png)

1. The link for `flatMap` contains the text `flatMap] or` and links to the bind function on MDN.
2. `bind` is not a link, but should link to the bind function on MDN.
> This is according to the docs: https://github.com/true-myth/true-myth/blob/master/src/maybe.ts#L829-L835

> ![image](https://user-images.githubusercontent.com/928502/48434436-8fb02e00-e72e-11e8-9426-f9e8a3f183a1.png)
1. `@typeparam` tag definitions are not being rendered correctly (docs seem to pull from `<T, U>` vs the [`@typeparam` tags](https://github.com/true-myth/true-myth/blob/master/src/maybe.ts#L858-L859)

Another `@typeparam` example from [`fromResult`](https://true-myth.js.org/modules/_maybe_.html#fromResult)
> ![image](https://user-images.githubusercontent.com/928502/48434612-0c430c80-e72f-11e8-8d56-dcfbb1fa8a30.png)
1. The definition for `E` is no rendered under the `Type parameters` header, but is rendered above it with a `typeparam` tag.

I'm not sure if this is an issue with typedoc or with the syntax you are using.

**Comment by chriskrycho** [comment]
Thank you! I'll try to get these fixed and republish the docs in the next day or two!

**Comment by chriskrycho** [comment]
Well, it took me an extra three months, but thank you very kindly for bringing these to our attention, @psyrendust! Just pushed up a commit (as part of 2.2.7) which fixed those issues. Let us know if you spot any others!
