### ISSUE TITLE
Result type guard is wrong

### ISSUE THREAD

**Issue by screendriver** [true-myth/true-myth#323]
In the past this was not possible because the TypeScript compiler did not allow it:

```ts
const foo = ok<string, string>('a');

console.log(foo.error);
```

But with `true-myth` `5.2.0` it is possible and I'm getting a runtime error `Cannot get the error of Ok`. Instead of a runtime error the compiler should warn here and force the type guard `if (foo.isErr) {}`.

**Comment by chriskrycho** [comment]
@screendriver interesting – is that right there the minimal example? Thank you for reporting it!
