### ISSUE TITLE
Idiomatic way to do complex IO?

### ISSUE THREAD

**Issue by dandrei** [true-myth/true-myth#33]
Hi, here's a use case where I need to perform some more complex IO (function names simplified here to be as generic as possible):

My app needs to fetch data from a third party API.
Since such calls are expensive, I want to first hit a local Mongo cache.
There are two cases:
1. If the Mongo cache contains the data, return it (`readMongo(id)` returns a `true-myth` `Result`)
2. If the Mongo cache is empty:
- call the API, get the result from there (`readAPI(id)` returns a `true-myth` `Result`)
- if valid, write it to Mongo (`writeMongo(id, data)` returns a `true-myth` `Result`)
- return the result, whatever it is (I'd also like this to be a `true-myth` `Result`)

As mentioned, all IO operations return `Result` types, that contain either the proper result of the operation or an `Error` object. How would you mix the three IO operations inside a single function that also returns a `Result`? (Which can be either the requested data as `Result.ok`, or a `Result.err` (containing all the various ways in which the three IO operations can fail)).

One way I see is to just go back to old imperative land and do dirty stuff like:

     if (cache.isErr()) { /* deal with the API*/ }

Is there a better, idiomatic way? Or is IO entirely to be avoided inside `true-myth` methods like `mapOrElse` etc.?

**Comment by chriskrycho** [comment]
Great question! I'll try to write up some notes on this by the end of the week! One extra complication here: I *assume* these are all async operations?

**Comment by dandrei** [comment]
Yes, that's right. Apart from the code that starts Nodejs, pretty much everything that happens, goes on in `async`/`await` land.

- They're all asynchronous operations (calls to DBs, external APIs, reading local files, etc.)
- I use them all with `async`/`await` (so the return type prior to `await` is a `Promise<Result<T, Error>>`)
- The `Promise` should never error out because all errors are contained within the `Result`.

**Comment by dandrei** [comment]
Another similar pattern is doing an upsert:
- See if a resource exists (usually DB entry)
- If it exists, do an update.
- If it doesn't exist, create it.
- Optionally, return the updated resource (by fetching it anew).

Again, both the read (checking if it exists) and the two possible write operations (updating or creating) are asynchronous and return a `Promise<Result<...>>`.

**Comment by chriskrycho** [comment]
Thanks for that clarification – I'll write up a pattern that *does work* with `Result`s, but this is also why I have been pondering a `Task`/`Future` type for the last long while (see #25). Turns out implementing that effectively is *way* more involved than implementing `Result` and `Maybe`, though, so I haven't gotten around to it.

**Comment by chriskrycho** [comment]
Sorry, this got buried among many other responsibilities! I've a draft of some blog posts that dig into this, but it'll likely be late October or November before I have them published.

**Comment by chriskrycho** [comment]
This obviously got dropped *hard*, but I haven't forgotten about it. I may do some follow-on work on #25 inspired by https://github.com/hojberg/seidr#asyncresult, which is fairly close to the experimental implementations I've done in this space in the past.
