### ISSUE TITLE
docs: markdown include is broken for maybe and result

### ISSUE THREAD

**Issue by psyrendust** [true-myth/true-myth#34]
Doc rendering issue where the intended markdown file is not being injected into the doc output and is instead replaced with just the include statement.

Pages affected:
* https://true-myth.js.org/modules/_maybe_.html
* https://true-myth.js.org/modules/_result_.html

### Screenshot from https://true-myth.js.org/modules/_maybe_.html
![image](https://user-images.githubusercontent.com/928502/53431118-be33db00-39a4-11e9-9836-662d7b2386fd.png)

**Comment by chriskrycho** [comment]
Ugh.

Any chance you're up for poking at this a bit and seeing if you can figure out why? I changed… *nothing* about that; best guess is there's a regression in TypeDoc. 😭

If not, no worries, but we'd welcome the help!

**Comment by chriskrycho** [comment]
Fixed! Thanks again for opening this – we really appreciate it! – and sorry about the delay in getting it fixed.
