### ISSUE TITLE
Applicative interface is wrong

### ISSUE THREAD

**Issue by snatvb** [true-myth/true-myth#38]
Hello, why your interface differ of Folktale maybe in applicative.
https://github.com/folktale/data.maybe/blob/master/lib/maybe.js#L206

Your suggestion:
```ts
const state: any = {
  b: {}
}
const a = Maybe.of(state).get('b').map(() => (num: number) => num * num)
const b = Maybe.of(234)
console.log(a.ap(b))
```

But I can't use that as chain.
I could do such:
```ts
const indentity = <T>(a: T): T => a
const state: any = {
  b: {}
}
const a = Maybe.of(state).get('b').map(() => (num: number) => num * num).unwrapOr(indentity)
const b = Maybe.of(234)
console.log(b.map(a))
```
But it's a crutch.
How it must be actually:
```ts
const state: any = {
  b: {}
}
const a = Maybe.of(state).get('b').map(() => (num: number) => num * num)
const c = Maybe.of(state).get('b').get('c').map(() => (num: number) => num * num)
const b = Maybe.of(234)
console.log(b.ap(a).ap(c))
```

**Comment by chriskrycho** [comment]
I'm not fully following what you're getting at here, but I see two basic problems with the examples you're providing:

1. Giving `state` the type `any` is going to make TS fail to resolve the types correctly, and that's almost certainly part of the problem; the compiler will guide you to the right invocation if you give it the correct type:

    ```ts
    const state: { b?: { c?: number } } = {
      b: {}
    };
    ```

    From what I can tell, the rest of it doesn't work the way you think it should *precisely* because of this. Doing `Maybe.of(state).get('b')` returns you a `Maybe<{ c?: number }>`, *not* a `Maybe<number>` – and you can't apply a function with the type `(n: number) => number` to `{ c?: number }`. That's why you have to do `.get('c')` again.

2. The function argument should not be a "thunk" but simply the function to apply. In other words, it shouldn't be `() => (num: number) => num * num` but simply `(num: number) => num * num`.

Once you make those changes, things work exactly as they should:

```ts
const c = Maybe.of(state).get('b').get('c');
const square = (n: number) => n * n;
Maybe.of(square).ap(c);
```

Happy to help clear up anything else, but the short version is: I believe this works as expected. The big takeaway here is: don’t type things as `any`!

**Comment by chriskrycho** [comment]
As a follow-up: we've made different tradeoffs than Folktale in where the implementation core is, but you can replace the implementation of [our `Just#ap` method][Just#ap] with the same implementation as Folktale's:

```ts
export class Just<T> implements MaybeShape<T> {
  // ...
  ap<A, B>(this: Maybe<(val: A) => B>, val: Maybe<A>): Maybe<B> {
    return val.map((this as Just<(val: A) => B>).value);
  }
}
```

This type-checks, and it works exactly the same as the current implementation (you can clone the repository, substitute that in, and run the tests and confirm this for yourself).

[Just#ap]: https://github.com/true-myth/true-myth/blob/66451a1778f1bc51bd49f9b8a307e9ce112de15b/src/maybe.ts#L291:L293

**Comment by snatvb** [comment]
> Giving state the type any is going to make TS fail to resolve the types correctly, and that's almost certainly part of the problem; the compiler will guide you to the right invocation if you give it the correct type:
This is just example, i understand that isn't right
I wrote about what apply must be use such:
```ts
const c = Maybe.of(state).get('b').get('c');
const square = (n: number) => n * n;
c.ap(square);
```
Then will I can do this:
```ts
type Data = { b?: { c?: number }, d?: number }
const data:  = {
  b: {}
};

const f(data: Data, state: number): number {
  const multC = Maybe.of(data).get('b').get('c').map((c) => (n) => n * n);
  const addD = Maybe.of(data).get('d').map((d) => (n) => n + d);
  const result = Maybe.of(state)
  return result.ap(multC).ap(addD).unwrapOr(c);
}
f({}, 8) // 8
f({ b: { c: 2 } }, 8) // 16
f({ b: { c: 2 } d: 4 }, 8) // 20
```
If `state.b.c` will undefined, this functions will not apply, to result. If I will working with objects, not apply some data is important for immutability

**Comment by chriskrycho** [comment]
You're just not lining up your types correctly. 😄 The interface works just the way it should; please dig in further with the types and docs! What you're wanting to do you *can* do if you pull in a library like Ramda or lodash and use their compose functions, but you cannot call `.ap` on a type which not a `Maybe<Function>`—that doesn't actually make sense, type-wise!

Here's how your example looks using the types correctly:

```ts
function f(data: Data, state: number): number {
  const multC = Maybe.of(data).get('b').get('c').map((c) => (n: number) => n * c);
  const addD = Maybe.of(data).get('d').map((d) => (n: number) => n + d);
  const result = Maybe.of(state);

  let multipliedC = multC.ap(result);
  let addedD = addD.ap(multipliedC);

  return addedD.or(multipliedC).unwrapOr(0);
}
```

Notice that the fact that this is not "chain-able" is not a bug: it's what the types require! And the functions *won't* be applied when the underlying value isn't present, exactly as you like.

What you're actually looking for here is a *compose* function. True Myth doesn't supply this because it's not trying to be a library for all functional programming—especially because other libraries already do this well and work perfectly nicely with True Myth. For example, if you were using Ramda's `compose` function, you could write this:

```ts
function f(data, state) {
  const multC = Maybe.of(data).get('b').get('c').map(c => n => n * c);
  const addD = Maybe.of(data).get('d').map(d => n => n + d);
  const result = Maybe.of(state);
  
  const bothOrEitherOr0 = pipe(
    Maybe.ap(multC),
    Maybe.ap(addD),
    Maybe.or(multC.ap(result)),
    Maybe.or(addD.ap(result)),
    Maybe.unwrapOr(0),
  );
  
  return bothOrEitherOr0(result);
}
```

This gives you exactly the results you're looking for, including lazy evaluation of the functions.

**Comment by snatvb** [comment]
Oh, okay, then I understood why you did such interface. Thank you for so good explanation, and your wasted time.
I got it.

**Comment by chriskrycho** [comment]
You're welcome!
