### ISSUE TITLE
Add back CJS support

### ISSUE THREAD

**Issue by codetheweb** [true-myth/true-myth#380]
Thanks for the great library!

Would it be possible to add back CJS support? There's still a lot of tooling that doesn't support ESM yet.

It wouldn't have to make the tooling for this library more complicated either; for example we use [tsup](https://tsup.egoist.sh/) which makes it super easy to bundle for both CJS & ESM: `tsup src/index.ts --format esm,cjs`.

Happy to open a PR for this.

**Comment by chriskrycho** [comment]
Thanks for the kind words!

Hmm, that's interesting. My *gut response* is to say "no", because anything which is on an appropriate version of Node *can* use this, and I want to help push the ecosystem forward into adopting ESM—and you *can* import ESM into CJS, it just requires using `import()` instead of `require()`.

That said, that's by no means a "hard no": do you have a use case of specific examples where transitioning is difficult and it's very valuable to still have a CJS bundle?

Also cc. @bmakuh!

**Comment by codetheweb** [comment]
It's a bit of a long story.

We use [esbuild-runner](https://github.com/folke/esbuild-runner) for on-the-fly TS transpilation during tests. However, it assumes that all dependencies listed in `package.json` are CJS and thus fair game to exclude from the final bundle--resulting in the output containing `require('true-myth')`. The solution in this case was to fork `esbuild-runner` and add an option to force bundling of specific ESM packages, but it doesn't seem to be actively maintained anymore so I doubt our changes will ever make it upstream. Why are we still using what seems to be an unmaintained package? Other alternatives like `ts-node` or `esbuild-register` don't seem to resolve our monorepo'd `tsconfig.json`'s paths correctly. Obviously the solution is to move to a new maintained package and provide fixups if it doesn't work properly, but there's only so much time you can spend on tooling madness per week before you have to move on. 😛 

I know this is kind of a weird example, but I think it does support my view that the ecosystem is not quite ready yet for packages to drop CJS. But as I'm typing this I'm realizing that this is more a personal opinion rather than an objective fact, so take it or leave it. 😃

**Comment by bmakuh** [comment]
Hey @codetheweb, sorry for just now responding. Like @chriskrycho my gut instinct is also probably "no," but on the other hand I've been in places before where I'm trying to upgrade something like a webpack plugin that does something funky and relies on some quirk in an older version of Node or something like that. So I hear you when you say that sometimes the ecosystem can lag behind the times in weird ways. Before we go down the road of adding back CJS support, though, I guess one thing I wonder is would it be fine to just stick with True Myth 4 for your use case? True Myth 5 adds _some_ new things but in general it's not a night and day difference from the last major version—the headline feature mostly was simplifying down to only ESM, haha. My thought is that if TM@4 has suited your needs up until now, would it be possible to hang around on that version until stuff like ts-node or esbuild-register could support monorepos? I only say that getting TM@5 to work with your use case will require a PR either way—a PR to add back CJS support here, or a PR on ts-node or esbuild-register to support monorepos (and the latter PR seems like it would help out other folks in the world too). Thoughts?

**Comment by codetheweb** [comment]
Yeah, I think v4 will probably work fine for now.

Thank you!

**Comment by evantill** [comment]
> Thanks for the kind words!
> 
> Hmm, that's interesting. My _gut response_ is to say "no", because anything which is on an appropriate version of Node _can_ use this, and I want to help push the ecosystem forward into adopting ESM—and you _can_ import ESM into CJS, it just requires using `import()` instead of `require()`.
> 
> That said, that's by no means a "hard no": do you have a use case of specific examples where transitioning is difficult and it's very valuable to still have a CJS bundle?
> 
> Also cc. @bmakuh!

Hi, just a feedback of a newbie in typescript : ESM module is really nice but the tools are not ready.
Forcing to use ot like an ESM module is just too early. Especially using typescript as it is easy to transpile something compatible with cjs but keep the target of ESM in the sources.

I have hitted so much bugs related (since 2 days) to go ESM only that I will give up this path.
The biggest problem was regarding confguring jest (also a great tool by the way).

**Comment by bmakuh** [comment]
Hey @evantill, thanks for the feedback. I apologize for the trouble! For what it's worth, you can totally use the 5.x line; it should be more than adequate. [We made a note about this in the readme](https://github.com/true-myth/true-myth#overview-) but it's pretty easy to overlook.

**Comment by evantill** [comment]
Thanl you. for your response, ans thank you for this great project

**Comment by chriskrycho** [comment]
FYI, I've revisited this (as even some of my own projects are blocked on this!) and expect to publish a 7.0 release including #567 (the only breaking change will be on the technicality of dropping Node versions earlier than Node 18 LTS), which should allow CJS consumption.
