### ISSUE TITLE
Support for async operations?

### ISSUE THREAD

**Issue by kee-oth** [true-myth/true-myth#426]
Hi!

I'm using and enjoying True Myth so far and I was wondering if there were any plans for async support? Maybe some kind of async `Result` or an `IO` monad?

Thanks!

**Comment by chriskrycho** [comment]
Thanks for the kind words! Summary of the current status is: neither @bmakuh nor I currently has time to implement it *or* the need for it in our current work, but we’re open to someone else contributing it. There is some discussion of it over at #208. Closing this in favor of that discussion; feel free to comment there!
