### ISSUE TITLE
Typescript configuration docs are not clear

### ISSUE THREAD

**Issue by mbylstra** [true-myth/true-myth#466]
I'm struggling to get true-myth to work in our code base since the v5 upgrade that removed support for commonJS.

In https://github.com/true-myth/true-myth#requirements it says:

```
    tsconfig.json:
        moduleResolution: "Node16"
        type: "module" (or else use import() to import True Myth into a commonJS build)
```

What is `type: "module"`? The `compilerOptions` for tsconfig does not have seem to have a property named `type`: https://www.typescriptlang.org/tsconfig#compilerOptions. There is a property named `module` though (is this what is meant? What value should be used? https://www.typescriptlang.org/tsconfig#module).

No matter what I try, I get  "Internal Error: Must use import to load ES Module"

This is an example of an import in one of my .ts files: `import { Result, Maybe } from "true-myth"`

**Comment by chriskrycho** [comment]
That's a reference to the `package.json` setting for `type`. Sorry that's unclear! I'll add a link to the corresponding Node docs!
