### ISSUE TITLE
Question: safely convert data

### ISSUE THREAD

**Issue by eikooc** [true-myth/true-myth#47]
I have a question of how to safely get or convert some data to another. I know the following code fails, but I was thinking something along these lines: 
```
Maybe.of({a: "a"}).map(x => x.b)
```
Another question. Is the above code supposed to throw an error? `Error: Tried to construct 'Just' with 'null' or 'undefined'`

Issue #46 is related but not entirely the same, that is a feature request.

**Comment by chriskrycho** [comment]
Sorry, just now saw this issue opened up.

The way you can write this is:

```ts
interface Dict<T> {
  [key: string]: T | null | undefined;
}

let maybeObj = Maybe.of({a: 'a'} as Dict<string>);
let maybeA = maybeObj.get('a'); // Just('a')
let maybeB = maybeObj.get('b'); // Nothing
```

If you're using the latest version of True Myth and a reasonably recent version of TypeScript with `strict: true` set in your `tsconfig.json`, the version you supplied *should* fail at type-checking time; it will *also* fail with a runtime error as you noted.

The idea in general is to make it so that these errors all get caught at compile time instead of runtime.

**Comment by chriskrycho** [comment]
(Note that I've closed the issue, but please feel free to ask further questions!)

**Comment by eikooc** [comment]
Thanks @chriskrycho but what if I want to convert multiple values from an object? (Just to clarify, the data might fail at run-time because this is external data I fetch).

Example: `Maybe.of({a: "a"}).map(x => ({a: x.a, b: x.b, prop: x.nested.prop}))`

Is there another way to go about this? As the same errors apply to this example

**Comment by chriskrycho** [comment]
At some point, you're going to need to write types to describe the shape of the data you're getting. In any case you can't use `map` that way and get a type-safe result back that has `Maybe` everywhere you want; it's simply not possible—and there's no possible implementation which could *make* it possible. You could write this:

```ts
Maybe.of(someResponse).map(responseData => ({
  a: Maybe.of(responseData.a),
  b: Maybe.of(responseData.b),
  prop: Maybe.of(responseData.nested).get('prop'),
}));
```

That's annoyingly noisy, of course, but you have to have *some* way to map each property to a `Maybe`.

In principle, we could write a `deepMaybeify`, but the performance for the type-checking on it would likely be prohibitive, and in truth you almost certainly don't *want* a bunch of deeply-nested properties to all become `Maybe` for lots of reasons.

In the data-fetching scenario, what you're actually looking for is almost certainly not a bunch of `Maybe` data, unless that's actually correct in how you're thinking about your domain model locally. Instead, you should think about how you want your data modeled, and then write functions which can *either* produce that (including `Maybe`s or not as makes sense) *or* produce errors. For that, you'll be better using `Result`s.

(I actually have a couple blog posts about this I'm working on, but they're on the back burner at the moment and I probably won't get to them until late October.)
