### ISSUE TITLE
true-myth.js.org is down

### ISSUE THREAD

**Issue by curran** [true-myth/true-myth#476]
![image](https://user-images.githubusercontent.com/68416/208196058-ea421ac0-6f31-41fb-914f-1a7e9dbc7a2d.png)

https://true-myth.js.org/ appears broken at the moment, JFYI

**Comment by chriskrycho** [comment]
Huh. Weird. Thank you for the heads up! I'll try to poke at it but it's apt to be later this week or sometime next.

**Comment by chriskrycho** [comment]
I'm hoping [this GH Actions run](https://github.com/true-myth/true-myth/actions/runs/3734735869) will get things back to working, and I can dig in more later when I have time.

**Comment by chriskrycho** [comment]
That did indeed fix it! 😅 Thanks again for the report! I'll still poke at what went wrong in the future, but at least the docs are back up!
