### ISSUE TITLE
Switch to Vitest

### ISSUE THREAD

**Issue by chriskrycho** [true-myth/true-myth#526]
It has the same APIs as Jest, but is *way* faster and ships types natively instead of requiring a `@types` package.

The work to be done:

- Add Vitest and update all tests to use its imports instead.
- Update the CI config.
- Drop `jest` and `@types/jest` from `package.json`.

**Comment by jm4rtinez** [comment]
Heya, I'll take a stab at this one!

**Comment by chriskrycho** [comment]
Awesome! I’ll take a look at the PR shortly—thanks so much!

**Comment by dagilleland** [comment]
@chriskrycho - Friendly "bump" and upvote for Vitest - looking forward to the merge
