### ISSUE TITLE
Maybe.transposeArray documentation use wong method name

### ISSUE THREAD

**Issue by evantill** [true-myth/true-myth#540]
`Maybe.transposeArray` documentation use the wrong method name `arrayTranspose`

I can fix it with a pull request

**Comment by evantill** [comment]
I can not use the import like in the example:

```ts
import Maybe from 'true-myth/maybe';

let valid = [Maybe.just(2), Maybe.just('three')];
let allJust = Maybe.transposeArray(valid); // => Just([2, 'three']);
let invalid = [Maybe.just(2), Maybe.nothing<string>()];

let mixed = Maybe.arrayTranspose(invalid); // => Nothing
  ```

instead this work:
```ts
import {Maybe,transposeArray} from "true-myth/maybe";

let valid = [Maybe.just(2), Maybe.just("three")];
let allJust = transposeArray(valid); // => Just([2, 'three']);
let invalid = [Maybe.just(2), Maybe.nothing<string>()];
```

Should I change the example code ? or the probleme is in an other place ?

**Comment by chriskrycho** [comment]
Hi @evantill – sorry, had *so* many GH notifications that I only saw this one (buried!) just now. You are 100% correct that the example code is wrong; what we have there *used* to work but no longer does after some refactors we did. If you open a PR, I'll make sure it gets merged and published!
