### ISSUE TITLE
Please bring back CommonJS exports 🙏 

### ISSUE THREAD

**Issue by erikshestopal** [true-myth/true-myth#550]
Hey all - and thanks for the great library! 

I'd like to request that you bring back CJS exports. Although I'm totally on board the ESM train, I'm maintaining an application that runs in the browser and works great with modules but also has has a test suite that uses `playwright` in a Node environment that breaks because of a `require() of ES Module` error.

**Comment by AniAleks** [comment]
Pls accept this message as a  gentle nudge ;)

**Comment by chriskrycho** [comment]
@erikshestopal We will consider it – I have hit annoying compatibility issues myself with it, so I sympathize! I cannot promise anything specific (including timeline) but I think it should be possible to publish a dual-mode package with a minimum of hassle, and the ecosystem has moved *much* more slowly on this front than I hoped. I'll follow up here if it changes!

**Comment by chriskrycho** [comment]
Addressing this via #567. I plan to get out a 7.0 release with this included, and which will only be breaking by dint of dropping support for earlier Node versions. 🎉
