### ISSUE TITLE
Bug: Maybe.map compiles when the function returns `void` or `undefined` 

### ISSUE THREAD

**Issue by aThorp96** [true-myth/true-myth#753]
The following code compiles, but the compiler should throw a type warning since you cannot create a `Maybe<void>` or `Maybe<undefined>:
```typescript
import { Maybe } from 'true-myth';

Maybe.of(123).map((n) => n**2).map(console.log);

// Or even
Maybe.of(123).map((_) => null);
Maybe.just(null);
```

Running the above code gives the following error: `Error: attempted to call "just" with undefined`

**Comment by chriskrycho** [comment]
Thanks for the bug report! I'll dig into it and see if we can prevent it. What version(s) of TS do you see this on? (We have historically done things to prevent this, but I don’t think we have explicit test coverage against it, so I will make sure we fix that as part of this.)

**Comment by chriskrycho** [comment]
It will happen on basically *any* version of TS, actually, having looked at the code! I will try to fix this and get a bug fix release out tomorrow or Monday!

**Comment by chriskrycho** [comment]
Fixed via #755 and released in 7.2.1!

**Comment by aThorp96** [comment]
Thank you so much!

**Comment by chriskrycho** [comment]
Thanks for the report! Was glad we could fix it!
