### ISSUE TITLE
Return error-free type in the `Result.ok` method

### ISSUE THREAD

**Issue by auvred** [true-myth/true-myth#788]
Imagine we have function `someFunc` that takes `Result<...>` as an argument, and we want to infer "ok" and "error" types of this result argument:

```ts
import { Result } from 'true-myth'

function someFunc<Ok extends number, Err extends string>(result: Result<Ok, Err>) {
  // ...
}

someFunc(Result.ok(1))
//        ^ Argument of type 'Result<1, unknown>' is not assignable to parameter of type 'Result<1, string>'.
//            Type 'Ok<1, unknown>' is not assignable to type 'Result<1, string>'.
//              Type 'Ok<1, unknown>' is not assignable to type 'Ok<1, string>'.
//                Type 'unknown' is not assignable to type 'string'.(2345)

someFunc(Result.ok<number, never>(1))
//        ^ all is fine

someFunc(Result.err('error'))
//        ^ Argument of type 'Result<unknown, "error">' is not assignable to parameter of type 'Result<number, "error">'.
//            Type 'Ok<unknown, "error">' is not assignable to type 'Result<number, "error">'.
//              Type 'Ok<unknown, "error">' is not assignable to type 'Ok<number, "error">'.
//                Type 'unknown' is not assignable to type 'number'.(2345)

someFunc(Result.err<never, string>('error'))
//        ^ all is fine
```

[TS Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgJQKYGcCuAbeBfOAMyghDgHIYpNUBaEATxgAtyAoNwzAOwGMZgEbnHSlUAMR68APAHkA1nFQAPGKm4ATdHG6YQAI1RQANHACiUKEtXqtIqsG4BzAHwAKKBhwwAXCi+4cvKmFlAuAJSIbHBwAPSxcAB0yWx4HKIgElJuaFi4iRDybgCM4eFs8TFVVQB6cACCUE566vAQhHAwDGCoFLne0sWmPPLcEADu3C7kcMDaY-AAhujowE7ci-rYvTAQcGCLUIuZalbtnd295P2BQ-ZQjq7kiRUJ1e8xACqXFAqDw9xRhMpjM5joIEsVmsNlsdnsuj0+gEYP97o9pi9Kh9sd9EeQ-ncRmNJtNZvMIXBlqt1pttp14T98fJUegHM4Ma9sVy4LirkTgaDyZDqTC6bsLnjWQ9nM83AAmADMABYAKzlNgZLJ8HLIgrM3QGIymbioABuRncpXKWI+dUW2GwZKIjlQ6TEkm1NxgiSMUDc5F90HIZU52LqjWamW4bQ6CKuXuk-MmpgARIGoCnSWCFpSoTTYfT9odjqhTnBznGkXkUQbDCY4GnLNBM89Q9yeYy-knuKn0y2nTmqdDaXCJfHkdJa0aG32OTb2x28V3AcSezOmxms0LcyKR4XK0zJ3o672Ny3MW8F1VeRRu4LwcLhwXxQep1BZYrVerNR7eDrqz6liTma05Sui-rpsG1qXu8doOk6hAukAA)

The issue is that these type parameters in (`E` in `ok` and `T` in `error`) methods declarations have no default value and are not used in argument types, so they're inferred as `unknown`. Although when calling `Result.ok()` I expect to get `Result<..., never>`, not `Result<..., unknown>`, since the `ok` method by its definition cannot return any errors! 

I suggest adding a default type for type parameters in places like this to avoid those annoying errors:
```diff
-  static ok<T, E>(value: T): Result<T, E>;
+  static ok<T, E = never>(value: T): Result<T, E>;
```
https://github.com/true-myth/true-myth/blob/87e12dd509bbd10e071c96feaa40bfb070b77831/src/result.ts#L87

**Comment by chriskrycho** [comment]
Ah, that’s a great idea! If you’d like to open a PR for it, I’ll happily review it; otherwise I’ll see about adding it myself sometime soon.
